proyecto_covid/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from home import views

urlpatterns = [
    path('', views.index,name="index"),
    path('', include('registro.urls')),
    path('admin/', admin.site.urls),

]

registro/urls.py
from django.urls import path
from registro import views

app_name = 'registro'

urlpatterns = [
    path('registro/', views.registro,name='registro'),
    path('login/', views.login_usuario, name='login'),
    path('logout', views.logout_usuario, name='logout'),
]

home/models.py
from django.db import models

# Create your models here.

registro/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)



    def __str__(self):
        #return self.user.email
        return self.user.username

registro/forms.py
from django import forms
from django.contrib.auth.models import User
from registro.models import UserProfileInfo

class UserForm(forms.ModelForm):


    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ( 'username', 'first_name', 'last_name', 'email', 'password')
        labels = {
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'email': 'Correo Electrónico',
            'password': 'Contraseña'
        }

        widgets = {
                'username': forms.TextInput(attrs={'class': 'form-control'}),
                'first_name': forms.TextInput(attrs={'class': 'form-control'}),
                'last_name': forms.TextInput(attrs={'class': 'form-control'}),
                'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. algo@unison.mx'}),
                'password': forms.PasswordInput(attrs={'class': 'form-control'}),

            }

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

registro/views.py
from django.shortcuts import render
from registro.forms import UserForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from registro.models import UserProfileInfo
from home import views
# Create your views here.



@login_required
def logout_usuario(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def registro(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(request.POST)

        if user_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()


            registered = True

        else:
            print(user_form.errors)
    else:
        user_form = UserForm()


    return render(request,'registro/registro.html',{'user_form':user_form,'registered':registered})



def login_usuario(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('CUENTA NO ACTIVA')

        else:
            print("Alguien intentó ingresar y falló")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Datos invalidos para login")
    else:
        return render(request,'registro/login.html', {})

templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'home/style.css' %}"/>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Inicio</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li><a class="nav-link "href="{% url 'registro:logout' %}">Logout</a></li>
          {% else %}
          <li><a class="nav-link" href="{% url 'registro:login' %}">Login</a></li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'registro:registro' %}">Registro</a>
          </li>
          {% endif %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>


        </div>
      </nav>

      <div class="container">

        {% block body_block %}

        {% endblock %}
      </div>


    </body>
  </html>

templates/home/index.html
<!DOCTYPE html>
{% extends "home/base.html" %}
{% block body_block %}
{% load static %}

<div class="contenido">
      <ul class="lista-contenido" class= "list-group list-group-flush">
        <li class="list-group-item list-group-item-info"><a href="#">Espacio del Químico</a></li>
        <li class="list-group-item list-group-item-info"><a href="#">Consulta resultados de prueba Covid-19</a></li>
        <li class="list-group-item list-group-item-info"><a href="https://www.who.int/es/emergencies/diseases/novel-coronavirus-2019/advice-for-public/q-a-coronaviruses#:~:text=sintomas">Información sobre Covid-19</a></li>
        <li class="list-group-item list-group-item-info"><a href="https://www.unison.mx/wp-content/uploads/2020/06/Lineamientos-US-3.pdf">Lineamentos sobre regreso regreso a actividades</a></li>
      </ul>
</div>

<div class="Bienvenida">
  <div class="jumbotron">
    <h1>¡Bienvenido!</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  </div>

</div>

<div class="logo-unison">
  <img src="{% static 'home/unison.png' %}" alt="logo unison"/>
</div>

<style>
  img{
    opacity: 0.5;
    position: absolute;
    top: 0px;
    right: 50px;
    margin-top: 7%;
    width: 10%;
  }
</style>

{% endblock %}

templates/registro/login.html
<!DOCTYPE html>
{% extends "home/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Login</h1>
  <form class="" action="{% url 'registro:login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password: </label>
    <input type="password" name="password" value="">

    <input type="submit" name="" value="Login">

  </form>

</div>
{% endblock %}

templates/registro/registro.html
<!DOCTYPE html>
{% extends "home/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    {% if registered %}
    <h1>¡Gracias por registrarse!</h1>
    {% else %}
      <h1>Registro</h1>
      <h3>Llene el siguiente formulario:</h3>
      <form class="form-group">
        <form method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          <input type="submit" name="" class="btn btn-primary" value="Registrar">
        </form>
        {% endif %}
      </form>


  </div>
</div>



{% endblock %}